apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bcuttino2-poi-map-app-dev
  annotations:
    argocd/app-name: bcuttino2-poi-map-app-dev
    backstage.io/kubernetes-id: bcuttino2-poi-map-app
    backstage.io/kubernetes-namespace: bcuttino2
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/bcuttino2-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/bcuttino2/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/bcuttino2/deployments/bcuttino2-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/bcuttino2-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://bcuttino2-poi-map-app-bcuttino2.apps.j0i9yf30.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/bcuttino2"
  system: workshop-system-bcuttino2
  consumesApis:
    - gateway-api-bcuttino2
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-bcuttino2
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/bcuttino2"
